### PR TITLE
fix: Do not convert TAC assuming decimal

### LINKED ISSUE #976: Paging not working v1.1.0
### Description

Hello team,
the paging is not working again. It was already solved, but when I upgraded to v1.1.0 the paging is not working.

In the log file I can see following errors:

```
ebpf/pdr.go:184 could not add gnb IP to neighbour list  {"component": "UPF", "IP": "192.168.99.81", "error": "could not add neighbour"}
upf/upf.go:312  Received notification for       {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:315  Notifying SMF of downlink data  {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
context/amf_ue.go:433   set ongoing procedure   {"component": "AMF", "AMF_UE_NGAP_ID": "AMF_UE_NGAP_ID:2", "supi": "260249000000001", "ongoingProcedure": "Paging", "previousOnGoingProcedure": "Nothing"}
upf/upf.go:319  Failed to send downlink data notification       {"component": "UPF", "error": "failed to send PFCP Session Report Request to smf: failed to send N1N2MessageTransfer to AMF: build paging error: SEQUENCE OF Size is lower than lowerbound"}
upf/upf.go:312  Received notification for       {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:315  Notifying SMF of downlink data  {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
context/amf_ue.go:433   set ongoing procedure   {"component": "AMF", "AMF_UE_NGAP_ID": "AMF_UE_NGAP_ID:2", "supi": "260249000000001", "ongoingProcedure": "Paging", "previousOnGoingProcedure": "Nothing"}
upf/upf.go:319  Failed to send downlink data notification       {"component": "UPF", "error": "failed to send PFCP Session Report Request to smf: failed to send N1N2MessageTransfer to AMF: build paging error: SEQUENCE OF Size is lower than lowerbound"}
upf/upf.go:312  Received notification for       {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:315  Notifying SMF of downlink data  {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:319  Failed to send downlink data notification       {"component": "UPF", "error": "failed to send PFCP Session Report Request to smf: failed to send N1N2MessageTransfer to AMF: higher priority request ongoing"}
upf/upf.go:312  Received notification for       {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:315  Notifying SMF of downlink data  {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:319  Failed to send downlink data notification       {"component": "UPF", "error": "failed to send PFCP Session Report Request to smf: failed to send N1N2MessageTransfer to AMF: higher priority request ongoing"}
upf/upf.go:312  Received notification for       {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:315  Notifying SMF of downlink data  {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}
upf/upf.go:319  Failed to send downlink data notification       {"component": "UPF", "error": "failed to send PFCP Session Report Request to smf: failed to send N1N2MessageTransfer to AMF: higher priority request ongoing"}
upf/upf.go:312  Received notification for       {"component": "UPF", "SEID": 1, "PDRID": 2, "QFI": 1}


```

[paging_v1.1.0.txt](https://github.com/user-attachments/files/24821522/paging_v1.1.0.txt)

### Environment

Docker on Ubuntu 24.04
{"component": "Ella", "version": "v1.1.0", "revision": "d1a8b5eb5fca31427c6026a903ea45c948cb5b8b"}

### Reproduction Steps

Attach, wait for inactivity timer, trigger ping traffic from external server to UE_ip.

### Expected Behavior

Paging should work as previously.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
# Description

Ella Core forces the TAC to be configured as a 6 digit hexadecimal string. However, when the UE registered, we converted the TAC received from the database to an hexadecimal string, assuming decimal. This worked fine for TACs `000001-000009`, but broke for all the other possible values. As an example, using TAC `000064` in the operator configuration would result in converting it to `000040` before comparing it to the TAC used by the UE.

This issue caused a UE using a mishandled TAC to have an empty registration area. This then broke building paging messages, as the registration area is required.

In the `BuildPaging` function, we only checked that the registration area was not nil before trying to build the message, causing an error further down the chain that was not clear. This PR also fixes that check, ensuring that this particular issue logs a clearer error message.

fixes #976 

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: internal/amf/context/amf_ue.go
Comment (gruyaume) [inline internal/amf/context/amf_ue.go:1]: Thank you very much for the fix. I think I may have introduced this issue when addressing https://github.com/ellanetworks/core/issues/926

File: internal/amf/context/amf_ue.go [hunk 1]
```diff
@@ -194,15 +193,6 @@ func (ue *AmfUe) AllocateRegistrationArea(supportedTais []models.Tai) {
 	taiList := make([]models.Tai, len(supportedTais))
 	copy(taiList, supportedTais)
 
-	for i := range taiList {
```
Comment (gruyaume) [inline internal/amf/context/amf_ue.go:197]: I like that the fix simplifies things (i.e. removes unnecessary conversion)

File: internal/amf/nas/gmm/handle_identity_response_test.go [hunk 2]
```diff
@@ -242,7 +242,7 @@ func TestHandleIdentityResponse_AuthenticationProcess_AuthenticationRequest(t *t
 				Mcc:           "001",
 				Mnc:           "01",
 				Sst:           1,
-				SupportedTACs: "[\"1\"]",
+				SupportedTACs: "[\"000001\"]",
```
Comment (gruyaume) [inline internal/amf/nas/gmm/handle_identity_response_test.go:245]: Can we add a test with something else than `000001` (ex.  `000064` is used by VergeWave)

Comment (ghislainbourgeois) [reply internal/amf/nas/gmm/handle_identity_response_test.go:245]: I modified one of the registration tests to use `CAFE64`.
