### PR TITLE
fix: Add gateways from routes on relevant interfaces to neighbours

### LINKED ISSUE #729: N6 interface - problem with ARP
The traffic forwading from N3 do N6 do not work if destination gw mac address is not in mac table. It looks like the kernel do not send ARP request to the route gw when XDP traffic is sent.   

This is example routing table (the iperf3 server has address 80.80.80.80)
```
root@solidrun02:/etc# ip route
default via 192.168.99.1 dev eth1 proto static
10.6.0.0/24 dev veth0upf proto kernel scope link src 10.6.0.5
80.80.80.80 via 192.168.99.57 dev eth1 proto static
192.168.9.0/24 dev eth5 proto kernel scope link src 192.168.9.10
192.168.99.0/24 dev eth1 proto kernel scope link src 192.168.99.80
root@solidrun02:/etc# ip neig
10.6.0.99 dev veth0upf lladdr 16:e8:28:f8:f1:2a REACHABLE
192.168.99.1 dev eth1 lladdr 00:08:a2:12:07:26 DELAY
192.168.99.22 dev eth1 lladdr 30:9c:23:22:8a:97 REACHABLE
192.168.99.81 dev eth1 lladdr 2a:38:fb:dd:8c:46 STALE
fe80::ca7f:54ff:fe56:589c dev eth1 lladdr c8:7f:54:56:58:9c STALE
fe80::14e8:28ff:fef8:f12a dev veth0upf lladdr 16:e8:28:f8:f1:2a STALE
fe80::ca7f:54ff:fe56:589c dev eth2 lladdr c8:7f:54:56:58:9c STALE
```
The packets are not send to N6 interfece until the MAC addres of 192.168.99.57 appear in MAC table.
I had to manually ping 192.168.99.57 to make traffic running.

```
root@solidrun02:/etc# ping -c 1 192.168.99.57
PING 192.168.99.57 (192.168.99.57): 56 data bytes
64 bytes from 192.168.99.57: seq=0 ttl=64 time=0.159 ms

--- 192.168.99.57 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.159/0.159/0.159 ms
root@solidrun02:/etc# ip neig
10.6.0.99 dev veth0upf lladdr 16:e8:28:f8:f1:2a DELAY
192.168.99.1 dev eth1 lladdr 00:08:a2:12:07:26 REACHABLE
192.168.99.57 dev eth1 lladdr 50:7c:6f:82:f6:42 DELAY
192.168.99.22 dev eth1 lladdr 30:9c:23:22:8a:97 REACHABLE
192.168.99.81 dev eth1 lladdr 2a:38:fb:dd:8c:46 STALE
fe80::8613:9fff:fe3e:358a dev eth2 lladdr 84:13:9f:3e:35:8a STALE
fe80::ca7f:54ff:fe56:589c dev eth1 lladdr c8:7f:54:56:58:9c STALE
fe80::14e8:28ff:fef8:f12a dev veth0upf lladdr 16:e8:28:f8:f1:2a STALE
fe80::8613:9fff:fe3e:358a dev eth1 lladdr 84:13:9f:3e:35:8a STALE
fe80::ca7f:54ff:fe56:589c dev eth2 lladdr c8:7f:54:56:58:9c STALE
```

I don't know what causes it? Is it the kernel version problem or eBPF/XDP architecture design?

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
# Description

Because we use XDP for the UPF pipeline, packets are routed without the usual kernel involvment. This means that the kernel will not send the ARP requests to the gateways that are necessary for routing to work from the UPF traffic. External intervention was necessary, either from network traffic or administrative actions.

This commit makes Ella Core add the gateways to the neighbour table with the `use` flag, ensuring the kernel will run the required ARP requests in the background.

We first add the gateway to the neighbour table anytime we create a route, ensuring that routes added from the interface will work immediately.

We also inspect all routes with gateways on N3 and N6, and try to add those gateways to the neighbour table during the route reconciliation process. This will cover all relevant routes that are not managed directly by Ella Core, for example routes received through DHCP.

fixes #729 

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: internal/kernel/routes.go [hunk 1]
```diff
@@ -205,3 +211,43 @@ func (rk *RealKernel) IsIPForwardingEnabled() (bool, error) {
...
+}
+
+func (rk *RealKernel) addNeighborForLink(neigh net.IP, link netlink.Link) {
+	// Tells the kernel that the gateway is in use, and ARP requests should be sent out
+	nlNeigh := netlink.Neigh{
+		LinkIndex: link.Attrs().Index,
+		IP:        neigh,
+		Flags:     netlink.NTF_USE,
+	}
+	if err := netlink.NeighAdd(&nlNeigh); err != nil {
```
Comment (gruyaume) [inline internal/kernel/routes.go:248]: These new commands work fine with confined snap?

Comment (ghislainbourgeois) [reply internal/kernel/routes.go:248]: It should be covered by the existing plug, but I will test now.

Comment (ghislainbourgeois) [reply internal/kernel/routes.go:248]: I can confirm that it works with the confined snap.
