### PR TITLE
fix: Properly send Configuration Update Command

### LINKED ISSUE #781: Paging do not work
### Description

The paging is not working. When the inactivity timer expires and there is traffic from internet to UE, the ellacore forwards the packets inside old GTP tunnel (which BTW should be released after UE release) . But the NGAP paging message is missing.

Image

### Environment

ellacore 0.3.1

### Reproduction Steps

setup a session with NAT disabled
wait for inactivity timer 
ping the UEip from external server

### Expected Behavior

paging should work,
no GTP traffic should be send to gnb after UE release, before new context is established

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
# Description

Ella Core previously did not send a Configuration Update Command to the UE for changing the GUTI after a successful network initiated Service Request procedure.

This changeset fixes the issue by adding support for sending this message and handling its response. The current implementation is very basic and was only tested for this particular use case.

We also added a way to keep track of an old GUTI, as both are the old and new GUTI should be considered valid by the AMF until acknowledged by the UE with a ConfigurationUpdateComplete.

fixes #781 

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: internal/amf/context/context.go [hunk 1]
```diff
@@ -279,17 +287,22 @@ func (context *AMFContext) InPlmnSupport(ctx ctxt.Context, snssai models.Snssai)
...
+// Looks up a UE by the provided GUTI.
+func (context *AMFContext) AmfUeFindByGutiLocal(guti string) (*AmfUe, bool) {
+	var (
+		ue *AmfUe
+		ok bool
+	)
+	context.UePool.Range(func(key, value any) bool {
 		candidate := value.(*AmfUe)
-		if ok = (candidate.Guti == guti); ok {
+		if ok = (candidate.Guti == guti || candidate.OldGuti == guti); ok {
```
Comment (gruyaume) [inline internal/amf/context/context.go:301]: Since we set the old guti to "" whenever we free it, is it possible for the UE to send an empty GUTI and for this function to return `true` whenever that's the case?

File: internal/amf/gmm/handler.go [hunk 2]
```diff
@@ -1509,6 +1518,7 @@ func HandleServiceRequest(ctx ctxt.Context, ue *context.AmfUe, anType models.Acc
 						cause := nasMessage.Cause5GMMProtocolErrorUnspecified
 						errCause = append(errCause, cause)
 					} else if ue.RanUe[anType].UeContextRequest {
+						ue.GmmLog.Debug("appending PDU session to context list")
```
Comment (gruyaume) [inline internal/amf/gmm/handler.go]: Do we really want this debug message?

File: internal/amf/gmm/handler.go [hunk 3]
```diff
@@ -1720,7 +1737,7 @@ func sendServiceAccept(ctx ctxt.Context, ue *context.AmfUe, anType models.Access
 			if err != nil {
 				return fmt.Errorf("error sending initial context setup request: %v", err)
 			}
-			ue.GmmLog.Info("Sent NGAP initial context setup request")
+			ue.GmmLog.Info("Sent NGAP initial context setup request with context list", zap.Int("len", len(ctxList.List)))
```
Comment (gruyaume) [inline internal/amf/gmm/handler.go]: We already have a log that will come from the ngap code. Here however we may want to log what's nas specific and can't be infered from the NGAP piece. Ex. `"Sent service accept with xyz"`

File: internal/amf/gmm/message/build.go [hunk 4]
```diff
@@ -619,3 +620,234 @@ func BuildRegistrationAccept(
...
+	m.GmmMessage.ConfigurationUpdateCommand = configurationUpdateCommand
+
+	m.SecurityHeader = nas.SecurityHeader{
+		ProtocolDiscriminator: nasMessage.Epd5GSMobilityManagementMessage,
+		SecurityHeaderType:    nas.SecurityHeaderTypeIntegrityProtectedAndCiphered,
+	}
+
+	b, err := nassecurity.Encode(ue, m)
+	if err != nil {
+		return nil, fmt.Errorf("BuildConfigurationUpdateCommand() err: %v", err), false
```
Comment (gruyaume) [inline internal/amf/gmm/message/build.go]:
```suggestion
		return nil, fmt.Errorf("could not encode NAS message: %v", err), false
```

File: internal/amf/gmm/handler.go [hunk 5]
```diff
@@ -1580,86 +1594,89 @@ func HandleServiceRequest(ctx ctxt.Context, ue *context.AmfUe, anType models.Acc
...
-						return err
+					omecSnssai := models.Snssai{
+						Sst: smInfo.SNssai.Sst,
+						Sd:  smInfo.SNssai.Sd,
+					}
+					if ue.RanUe[anType].UeContextRequest {
+						ue.GmmLog.Debug("appending PDU session to context list")
+						ngap_message.AppendPDUSessionResourceSetupListCxtReq(&ctxList, smInfo.PduSessionID, omecSnssai, nasPdu, n2Info)
+					} else {
+						ue.GmmLog.Debug("appending PDU session to su list")
```
Comment (gruyaume) [inline internal/amf/gmm/handler.go]: Do we need this log

File: internal/amf/gmm/handler.go [hunk 6]
```diff
@@ -1580,86 +1594,89 @@ func HandleServiceRequest(ctx ctxt.Context, ue *context.AmfUe, anType models.Acc
...
-					pduSessionID := uint8(smInfo.PduSessionID)
-					nasPdu, err = gmm_message.BuildDLNASTransport(ue, nasMessage.PayloadContainerTypeN1SMInfo, n1Msg, pduSessionID, nil)
-					if err != nil {
-						return err
+					omecSnssai := models.Snssai{
+						Sst: smInfo.SNssai.Sst,
+						Sd:  smInfo.SNssai.Sd,
+					}
+					if ue.RanUe[anType].UeContextRequest {
+						ue.GmmLog.Debug("appending PDU session to context list")
```
Comment (gruyaume) [inline internal/amf/gmm/handler.go]: Do we need this log

File: internal/amf/amf.go
Comment (gruyaume) [inline internal/amf/amf.go:1]: (unrelated to this file)

In the PR description, can you indicate that this change fixes the associated issue so that they are links and the issue gets closed as the fix gets merged.

File: internal/amf/gmm/handler.go (hunk 2 above)
Comment (ghislainbourgeois) [reply internal/amf/gmm/handler.go]: No, leftover from debugging, removing it

File: internal/amf/gmm/handler.go (hunk 5 above)
Comment (ghislainbourgeois) [reply internal/amf/gmm/handler.go]: No, leftover from debugging, removing it

File: internal/amf/gmm/handler.go (hunk 6 above)
Comment (ghislainbourgeois) [reply internal/amf/gmm/handler.go]: No, leftover from debugging, removing it

File: internal/amf/amf.go
Comment (ghislainbourgeois) [reply internal/amf/amf.go:1]: Done

File: internal/amf/context/context.go (hunk 1 above)
Comment (ghislainbourgeois) [reply internal/amf/context/context.go:301]: Currently no, this code is called from only 3 places, and they either build the GUTI or validate that it's not empty before calling. In any case, I just added a guard clause to prevent this from occurring in the future.

**Review by gruyaume — APPROVED** [review]
